site_name: Chip-8 Docs
nav:
    - Introduzione: 'index.md'
theme:
  name: terminal
  palette: pink
  features:
    - footer.prev_next
    - navigation.top.cursor_animation.hide
    - revision.date
    - style.links.underline.hide
plugins:
    - awesome-pages
